// src/scripts/data.ts

export const bangladeshData = [
    {
      division: "Barisal",
      division_bn: "বরিশাল",
      districts: [
        {
          district: "Barguna",
          district_bn: "বরগুনা",
          upazilas: [
            { upazila: "Amtali", upazila_bn: "আমতলী", postCode: "8710" },
            { upazila: "Bamna", upazila_bn: "বামনা", postCode: "8730" },
            { upazila: "Barguna Sadar", upazila_bn: "বরগুনা সদর", postCode: "8700" },
            { upazila: "Betagi", upazila_bn: "বেতাগী", postCode: "8740" },
            { upazila: "Patharghata", upazila_bn: "পাথরঘাটা", postCode: "8720" },
            { upazila: "Taltali", upazila_bn: "তালতলী", postCode: "8711" },
          ],
        },
        {
          district: "Barisal",
          district_bn: "বরিশাল",
          city_corporations: [
              { name: "Barishal City Corporation", name_bn: "বরিশাল সিটি কর্পোরেশন" }
          ],
          upazilas: [
            { upazila: "Agailjhara", upazila_bn: "আগৈলঝাড়া", postCode: "8240" },
            { upazila: "Babuganj", upazila_bn: "বাবুগঞ্জ", postCode: "8210" },
            { upazila: "Bakerganj", upazila_bn: "বাকেরগঞ্জ", postCode: "8280" },
            { upazila: "Banaripara", upazila_bn: "বানারীপাড়া", postCode: "8530" },
            { upazila: "Gaurnadi", upazila_bn: "গৌরনদী", postCode: "8230" },
            { upazila: "Hizla", upazila_bn: "হিজলা", postCode: "8290" },
            { upazila: "Barisal Sadar", upazila_bn: "বরিশাল সদর", postCode: "8200" },
            { upazila: "Mehendiganj", upazila_bn: "মেহেন্দিগঞ্জ", postCode: "8270" },
            { upazila: "Muladi", upazila_bn: "মুলাদী", postCode: "8250" },
            { upazila: "Wazirpur", upazila_bn: "উজিরপুর", postCode: "8220" },
          ],
        },
        {
          district: "Bhola",
          district_bn: "ভোলা",
          upazilas: [
            { upazila: "Bhola Sadar", upazila_bn: "ভোলা সদর", postCode: "8300" },
            { upazila: "Burhanuddin", upazila_bn: "বোরহানউদ্দিন", postCode: "8320" },
            { upazila: "Char Fasson", upazila_bn: "চরফ্যাশন", postCode: "8340" },
            { upazila: "Daulatkhan", upazila_bn: "দৌলতখান", postCode: "8310" },
            { upazila: "Lalmohan", upazila_bn: "লালমোহন", postCode: "8330" },
            { upazila: "Manpura", upazila_bn: "মনপুরা", postCode: "8350" },
            { upazila: "Tazumuddin", upazila_bn: "তজুমদ্দিন", postCode: "8360" },
          ],
        },
        {
          district: "Jhalokati",
          district_bn: "ঝালকাঠি",
          upazilas: [
            { upazila: "Jhalokati Sadar", upazila_bn: "ঝালকাঠি সদর", postCode: "8400" },
            { upazila: "Kathalia", upazila_bn: "কাঠালিয়া", postCode: "8430" },
            { upazila: "Nalchity", upazila_bn: "নলছিটি", postCode: "8420" },
            { upazila: "Rajapur", upazila_bn: "রাজাপুর", postCode: "8410" },
          ],
        },
        {
          district: "Patuakhali",
          district_bn: "পটুয়াখালী",
          upazilas: [
            { upazila: "Bauphal", upazila_bn: "বাউফল", postCode: "8620" },
            { upazila: "Dashmina", upazila_bn: "দশমিনা", postCode: "8630" },
            { upazila: "Galachipa", upazila_bn: "গলাচিপা", postCode: "8640" },
            { upazila: "Kalapara", upazila_bn: "কলাপাড়া", postCode: "8650" },
            { upazila: "Mirzaganj", upazila_bn: "মির্জাগঞ্জ", postCode: "8610" },
            { upazila: "Patuakhali Sadar", upazila_bn: "পটুয়াখালী সদর", postCode: "8600" },
            { upazila: "Rangabali", upazila_bn: "রাঙ্গাবালী", postCode: "8641" },
            { upazila: "Dumki", upazila_bn: "দুমকি", postCode: "8601" },
          ],
        },
        {
          district: "Pirojpur",
          district_bn: "পিরোজপুর",
          upazilas: [
            { upazila: "Bhandaria", upazila_bn: "ভান্ডারিয়া", postCode: "8550" },
            { upazila: "Kawkhali", upazila_bn: "কাউখালী", postCode: "8510" },
            { upazila: "Mathbaria", upazila_bn: "মঠবাড়িয়া", postCode: "8560" },
            { upazila: "Nazirpur", upazila_bn: "নাজিরপুর", postCode: "8540" },
            { upazila: "Pirojpur Sadar", upazila_bn: "পিরোজপুর সদর", postCode: "8500" },
            { upazila: "Nesarabad (Swarupkati)", upazila_bn: "নেছারাবাদ (স্বরূপকাঠি)", postCode: "8520" },
            { upazila: "Zianagar", upazila_bn: "জিয়ানগর", postCode: "8501" },
          ],
        },
      ],
    },
    {
      division: "Chittagong",
      division_bn: "চট্টগ্রাম",
      districts: [
        {
          district: "Bandarban",
          district_bn: "বান্দরবান",
          upazilas: [
            { upazila: "Alikadam", upazila_bn: "আলীকদম", postCode: "4650" },
            { upazila: "Bandarban Sadar", upazila_bn: "বান্দরবান সদর", postCode: "4600" },
            { upazila: "Lama", upazila_bn: "লামা", postCode: "4640" },
            { upazila: "Naikhongchhari", upazila_bn: "নাইক্ষ্যংছড়ি", postCode: "4660" },
            { upazila: "Rowangchhari", upazila_bn: "রোয়াংছড়ি", postCode: "4610" },
            { upazila: "Ruma", upazila_bn: "রুমা", postCode: "4620" },
            { upazila: "Thanchi", upazila_bn: "থানচি", postCode: "4630" },
          ],
        },
        {
          district: "Brahmanbaria",
          district_bn: "ব্রাহ্মণবাড়িয়া",
          upazilas: [
            { upazila: "Akhaura", upazila_bn: "আখাউড়া", postCode: "3450" },
            { upazila: "Bancharampur", upazila_bn: "বাঞ্ছারামপুর", postCode: "3420" },
            { upazila: "Brahmanbaria Sadar", upazila_bn: "ব্রাহ্মণবাড়িয়া সদর", postCode: "3400" },
            { upazila: "Kasba", upazila_bn: "কসবা", postCode: "3460" },
            { upazila: "Nabinagar", upazila_bn: "নবীনগর", postCode: "3410" },
            { upazila: "Nasirnagar", upazila_bn: "নাসিরনগর", postCode: "3440" },
            { upazila: "Sarail", upazila_bn: "সরাইল", postCode: "3430" },
            { upazila: "Ashuganj", upazila_bn: "আশুগঞ্জ", postCode: "3401" },
            { upazila: "Bijoynagar", upazila_bn: "বিজয়পুর", postCode: "3431" },
          ],
        },
        {
          district: "Chandpur",
          district_bn: "চাঁদপুর",
          upazilas: [
            { upazila: "Chandpur Sadar", upazila_bn: "চাঁদপুর সদর", postCode: "3600" },
            { upazila: "Faridganj", upazila_bn: "ফরিদগঞ্জ", postCode: "3650" },
            { upazila: "Haimchar", upazila_bn: "হাইমচর", postCode: "3660" },
            { upazila: "Haziganj", upazila_bn: "হাজীগঞ্জ", postCode: "3610" },
            { upazila: "Kachua", upazila_bn: "কচুয়া", postCode: "3630" },
            { upazila: "Matlab Dakshin", upazila_bn: "মতলব দক্ষিণ", postCode: "3620" },
            { upazila: "Matlab Uttar", upazila_bn: "মতলব উত্তর", postCode: "3621" },
            { upazila: "Shahrasti", upazila_bn: "শাহরাস্তি", postCode: "3640" },
          ],
        },
        {
          district: "Chittagong",
          district_bn: "চট্টগ্রাম",
          city_corporations: [
              { name: "Chattogram City Corporation", name_bn: "চট্টগ্রাম সিটি কর্পোরেশন" }
          ],
          upazilas: [
            { upazila: "Anwara", upazila_bn: "আনোয়ারা", postCode: "4376" },
            { upazila: "Banshkhali", upazila_bn: "বাঁশখালী", postCode: "4390" },
            { upazila: "Boalkhali", upazila_bn: "বোয়ালখালী", postCode: "4360" },
            { upazila: "Chandanaish", upazila_bn: "চন্দনাইশ", postCode: "4380" },
            { upazila: "Fatikchhari", upazila_bn: "ফটিকছড়ি", postCode: "4350" },
            { upazila: "Hathazari", upazila_bn: "হাটহাজারী", postCode: "4330" },
            { upazila: "Lohagara", upazila_bn: "লোহাগাড়া", postCode: "4396" },
            { upazila: "Mirsharai", upazila_bn: "মীরসরাই", postCode: "4320" },
            { upazila: "Patiya", upazila_bn: "পটিয়া", postCode: "4370" },
            { upazila: "Rangunia", upazila_bn: "রাঙ্গুনিয়া", postCode: "4360" },
            { upazila: "Raozan", upazila_bn: "রাউজান", postCode: "4340" },
            { upazila: "Sandwip", upazila_bn: "সন্দ্বীপ", postCode: "4300" },
            { upazila: "Satkania", upazila_bn: "সাতকানিয়া", postCode: "4386" },
            { upazila: "Sitakunda", upazila_bn: "সীতাকুণ্ড", postCode: "4310" },
            { upazila: "Karnaphuli", upazila_bn: "কর্ণফুলী", postCode: "4377" },
            // Chittagong City Corporation Thanas
            { upazila: "Akbar Shah", upazila_bn: "আকবর শাহ", postCode: "4207" },
            { upazila: "Bayazid", upazila_bn: "বায়েজীদ", postCode: "4210" },
            { upazila: "Bhujpur", upazila_bn: "ভুজপুর", postCode: "4331" },
            { upazila: "Chandgaon", upazila_bn: "চান্দগাঁও", postCode: "4212" },
            { upazila: "Chawkbazar", upazila_bn: "চকবাজার", postCode: "4203" },
            { upazila: "Double Mooring", upazila_bn: "ডাবল মুরিং", postCode: "4100" },
            { upazila: "EPZ", upazila_bn: "ইপিজেড", postCode: "4223" },
            { upazila: "Halishahar", upazila_bn: "হালিশহর", postCode: "4216" },
            { upazila: "Khulshi", upazila_bn: "খুলশী", postCode: "4225" },
            { upazila: "Kotwali", upazila_bn: "কোতোয়ালী", postCode: "4000" },
            { upazila: "Pahartali", upazila_bn: "পাহাড়তলী", postCode: "4202" },
            { upazila: "Panchlaish", upazila_bn: "পাঁচলাইশ", postCode: "4209" },
            { upazila: "Patenga", upazila_bn: "পতেঙ্গা", postCode: "4222" },
          ],
        },
        {
          district: "Comilla",
          district_bn: "কুমিল্লা",
          city_corporations: [
              { name: "Cumilla City Corporation", name_bn: "কুমিল্লা সিটি কর্পোরেশন" }
          ],
          upazilas: [
            { upazila: "Barura", upazila_bn: "বরুড়া", postCode: "3560" },
            { upazila: "Brahmanpara", upazila_bn: "ব্রাহ্মণপাড়া", postCode: "3526" },
            { upazila: "Burichang", upazila_bn: "বুড়িচং", postCode: "3520" },
            { upazila: "Chandina", upazila_bn: "চান্দিনা", postCode: "3510" },
            { upazila: "Chauddagram", upazila_bn: "চৌদ্দগ্রাম", postCode: "3550" },
            { upazila: "Daudkandi", upazila_bn: "দাউদকান্দি", postCode: "3580" },
            { upazila: "Debidwar", upazila_bn: "দেবিদ্বার", postCode: "3530" },
            { upazila: "Homna", upazila_bn: "হোমনা", postCode: "3540" },
            { upazila: "Laksam", upazila_bn: "লাকসাম", postCode: "3570" },
            { upazila: "Monohorgonj", upazila_bn: "মনোহরগঞ্জ", postCode: "3571" },
            { upazila: "Meghna", upazila_bn: "মেঘনা", postCode: "3581" },
            { upazila: "Muradnagar", upazila_bn: "মুরাদনগর", postCode: "3540" },
            { upazila: "Nangalkot", upazila_bn: "নাঙ্গলকোট", postCode: "3580" },
            { upazila: "Comilla Sadar", upazila_bn: "কুমিল্লা সদর", postCode: "3500" },
            { upazila: "Comilla Sadar South", upazila_bn: "কুমিল্লা সদর দক্ষিণ", postCode: "3501" },
            { upazila: "Titas", upazila_bn: "তিতাস", postCode: "3582" },
          ],
        },
        {
          district: "Cox's Bazar",
          district_bn: "কক্সবাজার",
          upazilas: [
            { upazila: "Chakaria", upazila_bn: "চকোরিয়া", postCode: "4740" },
            { upazila: "Cox's Bazar Sadar", upazila_bn: "কক্সবাজার সদর", postCode: "4700" },
            { upazila: "Kutubdia", upazila_bn: "কুতুবদিয়া", postCode: "4720" },
            { upazila: "Maheshkhali", upazila_bn: "মহেশখালী", postCode: "4710" },
            { upazila: "Ramu", upazila_bn: "রামু", postCode: "4730" },
            { upazila: "Teknaf", upazila_bn: "টেকনাফ", postCode: "4760" },
            { upazila: "Ukhia", upazila_bn: "উখিয়া", postCode: "4750" },
            { upazila: "Pekua", upazila_bn: "পেকুয়া", postCode: "4741" },
          ],
        },
        {
          district: "Feni",
          district_bn: "ফেনী",
          upazilas: [
            { upazila: "Chhagalnaiya", upazila_bn: "ছাগলনাইয়া", postCode: "3910" },
            { upazila: "Daganbhuiyan", upazila_bn: "দাগনভূঞা", postCode: "3920" },
            { upazila: "Feni Sadar", upazila_bn: "ফেনী সদর", postCode: "3900" },
            { upazila: "Parshuram", upazila_bn: "পরশুরাম", postCode: "3940" },
            { upazila: "Sonagazi", upazila_bn: "সোনাগাজী", postCode: "3930" },
            { upazila: "Fulgazi", upazila_bn: "ফুলগাজী", postCode: "3941" },
          ],
        },
        {
          district: "Khagrachhari",
          district_bn: "খাগড়াছড়ি",
          upazilas: [
            { upazila: "Dighinala", upazila_bn: "দীঘিনালা", postCode: "4420" },
            { upazila: "Khagrachhari Sadar", upazila_bn: "খাগড়াছড়ি সদর", postCode: "4400" },
            { upazila: "Lakshmichhari", upazila_bn: "লক্ষীছড়ি", postCode: "4450" },
            { upazila: "Mahalchhari", upazila_bn: "মহালছড়ি", postCode: "4410" },
            { upazila: "Manikchhari", upazila_bn: "মানিকছড়ি", postCode: "4460" },
            { upazila: "Matiranga", upazila_bn: "মাটিরাঙ্গা", postCode: "4440" },
            { upazila: "Panchhari", upazila_bn: "পানছড়ি", postCode: "4430" },
            { upazila: "Ramgarh", upazila_bn: "রামগড়", postCode: "4470" },
          ],
        },
        {
          district: "Lakshmipur",
          district_bn: "লক্ষ্মীপুর",
          upazilas: [
            { upazila: "Lakshmipur Sadar", upazila_bn: "লক্ষ্মীপুর সদর", postCode: "3700" },
            { upazila: "Raipur", upazila_bn: "রায়পুর", postCode: "3710" },
            { upazila: "Ramganj", upazila_bn: "রামগঞ্জ", postCode: "3720" },
            { upazila: "Ramgati", upazila_bn: "রামগতি", postCode: "3730" },
            { upazila: "Kamalnagar", upazila_bn: "কমলনগর", postCode: "3731" },
          ],
        },
        {
          district: "Noakhali",
          district_bn: "নোয়াখালী",
          upazilas: [
            { upazila: "Begumganj", upazila_bn: "বেগমগঞ্জ", postCode: "3820" },
            { upazila: "Chatkhil", upazila_bn: "চাটখিল", postCode: "3830" },
            { upazila: "Companyganj", upazila_bn: "কোম্পানীগঞ্জ", postCode: "3840" },
            { upazila: "Hatiya", upazila_bn: "হাতিয়া", postCode: "3850" },
            { upazila: "Senbagh", upazila_bn: "সেনবাগ", postCode: "3860" },
            { upazila: "Subarnachar", upazila_bn: "সুবর্ণচর", postCode: "3821" },
            { upazila: "Kabirhat", upazila_bn: "কবিরহাট", postCode: "3807" },
            { upazila: "Noakhali Sadar", upazila_bn: "নোয়াখালী সদর", postCode: "3800" },
            { upazila: "Sonaimuri", upazila_bn: "সোনাইমুড়ী", postCode: "3822" },
          ],
        },
        {
          district: "Rangamati",
          district_bn: "রাঙ্গামাটি",
          upazilas: [
            { upazila: "Bagaichhari", upazila_bn: "বাঘাইছড়ি", postCode: "4550" },
            { upazila: "Barkal", upazila_bn: "বরকল", postCode: "4530" },
            { upazila: "Kawkhali (Betbunia)", upazila_bn: "কাউখালী (বেতবুনিয়া)", postCode: "4510" },
            { upazila: "Belaichhari", upazila_bn: "বিলাইছড়ি", postCode: "4520" },
            { upazila: "Kaptai", upazila_bn: "কাপ্তাই", postCode: "4511" },
            { upazila: "Juraichhari", upazila_bn: "জুরাছড়ি", postCode: "4540" },
            { upazila: "Langadu", upazila_bn: "লংগদু", postCode: "4570" },
            { upazila: "Naniarchar", upazila_bn: "নানিয়ারচর", postCode: "4560" },
            { upazila: "Rajasthali", upazila_bn: "রাজস্থলী", postCode: "4512" },
            { upazila: "Rangamati Sadar", upazila_bn: "রাঙ্গামাটি সদর", postCode: "4500" },
          ],
        },
      ],
    },
    {
      division: "Dhaka",
      division_bn: "ঢাকা",
      districts: [
        {
          district: "Dhaka",
          district_bn: "ঢাকা",
          city_corporations: [
              { name: "Dhaka North City Corporation", name_bn: "ঢাকা উত্তর সিটি কর্পোরেশন" },
              { name: "Dhaka South City Corporation", name_bn: "ঢাকা দক্ষিণ সিটি কর্পোরেশন" }
          ],
          upazilas: [
            { upazila: "Dhamrai", upazila_bn: "ধামরাই", postCode: "1350" },
            { upazila: "Dohar", upazila_bn: "দোহার", postCode: "1330" },
            { upazila: "Keraniganj", upazila_bn: "কেরানীগঞ্জ", postCode: "1310" },
            { upazila: "Nawabganj", upazila_bn: "নবাবগঞ্জ", postCode: "1320" },
            { upazila: "Savar", upazila_bn: "সাভার", postCode: "1340" },
            // Dhaka City Corporation Thanas
            { upazila: "Adabor", upazila_bn: "আদাবর", postCode: "1207" },
            { upazila: "Badda", upazila_bn: "বাড্ডা", postCode: "1212" },
            { upazila: "Biman Bandar", upazila_bn: "বিমান বন্দর", postCode: "1229" },
            { upazila: "Bangshal", upazila_bn: "বংশাল", postCode: "1100" },
            { upazila: "Cantonment", upazila_bn: "ক্যান্টনমেন্ট", postCode: "1206" },
            { upazila: "Chawkbazar", upazila_bn: "চকবাজার", postCode: "1211" },
            { upazila: "Darus Salam", upazila_bn: "দারুস সালাম", postCode: "1216" },
            { upazila: "Demra", upazila_bn: "ডেমরা", postCode: "1360" },
            { upazila: "Dhanmondi", upazila_bn: "ধানমন্ডি", postCode: "1205" },
            { upazila: "Gendaria", upazila_bn: "গেণ্ডারিয়া", postCode: "1204" },
            { upazila: "Gulshan", upazila_bn: "গুলশান", postCode: "1212" },
            { upazila: "Hazaribagh", upazila_bn: "হাজারীবাগ", postCode: "1209" },
            { upazila: "Jatrabari", upazila_bn: "যাত্রাবাড়ী", postCode: "1362" },
            { upazila: "Kadamtali", upazila_bn: "কদমতলী", postCode: "1361" },
            { upazila: "Kafrul", upazila_bn: "কাফরুল", postCode: "1206" },
            { upazila: "Kalabagan", upazila_bn: "কলাবাগান", postCode: "1205" },
            { upazila: "Kamrangirchar", upazila_bn: "কামরাঙ্গীরচর", postCode: "1211" },
            { upazila: "Khilgaon", upazila_bn: "খিলগাঁও", postCode: "1219" },
            { upazila: "Khilkhet", upazila_bn: "খিলক্ষেত", postCode: "1229" },
            { upazila: "Kotwali", upazila_bn: "কোতোয়ালী", postCode: "1100" },
            { upazila: "Lalbagh", upazila_bn: "লালবাগ", postCode: "1211" },
            { upazila: "Mirpur", upazila_bn: "মিরপুর", postCode: "1216" },
            { upazila: "Mohammadpur", upazila_bn: "محمدপুর", postCode: "1207" },
            { upazila: "Motijheel", upazila_bn: "মতিঝিল", postCode: "1000" },
            { upazila: "New Market", upazila_bn: "নিউ মার্কেট", postCode: "1205" },
            { upazila: "Pallabi", upazila_bn: "পল্লবী", postCode: "1216" },
            { upazila: "Paltan", upazila_bn: "পল্টন", postCode: "1000" },
            { upazila: "Ramna", upazila_bn: "রমনা", postCode: "1217" },
            { upazila: "Rampura", upazila_bn: "রামপুরা", postCode: "1219" },
            { upazila: "Sabujbagh", upazila_bn: "সবুজবাগ", postCode: "1214" },
            { upazila: "Shah Ali", upazila_bn: "শাহ আলী", postCode: "1216" },
            { upazila: "Shahbagh", upazila_bn: "শাহবাগ", postCode: "1000" },
            { upazila: "Sher-e-Bangla Nagar", upazila_bn: "শেরেবাংলা নগর", postCode: "1207" },
            { upazila: "Shyampur", upazila_bn: "শ্যামপুর", postCode: "1204" },
            { upazila: "Sutrapur", upazila_bn: "সূত্রাপুর", postCode: "1100" },
            { upazila: "Tejgaon", upazila_bn: "তেজগাঁও", postCode: "1215" },
            { upazila: "Tejgaon Industrial Area", upazila_bn: "তেজগাঁও শিল্প এলাকা", postCode: "1208" },
            { upazila: "Turag", upazila_bn: "তুরাগ", postCode: "1230" },
            { upazila: "Uttar Khan", upazila_bn: "উত্তরখান", postCode: "1230" },
            { upazila: "Uttara", upazila_bn: "উত্তরা", postCode: "1230" },
            { upazila: "Vatara", upazila_bn: "ভাটারা", postCode: "1229" },
            { upazila: "Wari", upazila_bn: "ওয়ারী", postCode: "1203" },
          ],
        },
        {
          district: "Faridpur",
          district_bn: "ফরিদপুর",
          upazilas: [
            { upazila: "Alfadanga", upazila_bn: "আলফাডাঙ্গা", postCode: "7870" },
            { upazila: "Bhanga", upazila_bn: "ভাঙ্গা", postCode: "7830" },
            { upazila: "Boalmari", upazila_bn: "বোয়ালমারী", postCode: "7860" },
            { upazila: "Charbhadrasan", upazila_bn: "চরভদ্রাসন", postCode: "7810" },
            { upazila: "Faridpur Sadar", upazila_bn: "ফরিদপুর সদর", postCode: "7800" },
            { upazila: "Madhukhali", upazila_bn: "মধুখালী", postCode: "7850" },
            { upazila: "Nagarkanda", upazila_bn: "নগরকান্দা", postCode: "7840" },
            { upazila: "Sadarpur", upazila_bn: "সদরপুর", postCode: "7820" },
            { upazila: "Saltha", upazila_bn: "সালথা", postCode: "7841" },
          ],
        },
        {
          district: "Gazipur",
          district_bn: "গাজীপুর",
          city_corporations: [
              { name: "Gazipur City Corporation", name_bn: "গাজীপুর সিটি কর্পোরেশন" }
          ],
          upazilas: [
            { upazila: "Gazipur Sadar", upazila_bn: "গাজীপুর সদর", postCode: "1700" },
            { upazila: "Kaliakair", upazila_bn: "কালিয়াকৈর", postCode: "1750" },
            { upazila: "Kaliganj", upazila_bn: "কালীগঞ্জ", postCode: "1720" },
            { upazila: "Kapasia", upazila_bn: "কাপাসিয়া", postCode: "1730" },
            { upazila: "Sreepur", upazila_bn: "শ্রীপুর", postCode: "1740" },
          ],
        },
        {
          district: "Gopalganj",
          district_bn: "গোপালগঞ্জ",
          upazilas: [
            { upazila: "Gopalganj Sadar", upazila_bn: "গোপালগঞ্জ সদর", postCode: "8100" },
            { upazila: "Kasiani", upazila_bn: "কাশিয়ানী", postCode: "8130" },
            { upazila: "Kotalipara", upazila_bn: "কোটালীপাড়া", postCode: "8110" },
            { upazila: "Muksudpur", upazila_bn: "মুকসুদপুর", postCode: "8140" },
            { upazila: "Tungipara", upazila_bn: "টুঙ্গিপাড়া", postCode: "8120" },
          ],
        },
        {
          district: "Kishoreganj",
          district_bn: "কিশোরগঞ্জ",
          upazilas: [
            { upazila: "Austagram", upazila_bn: "অষ্টগ্রাম", postCode: "2350" },
            { upazila: "Bajitpur", upazila_bn: "বাজিতপুর", postCode: "2336" },
            { upazila: "Bhairab", upazila_bn: "ভৈরব", postCode: "2340" },
            { upazila: "Hossainpur", upazila_bn: "হোসেনপুর", postCode: "2320" },
            { upazila: "Itna", upazila_bn: "ইটনা", postCode: "2370" },
            { upazila: "Karimganj", upazila_bn: "করিমগঞ্জ", postCode: "2310" },
            { upazila: "Katiadi", upazila_bn: "কটিয়াদী", postCode: "2330" },
            { upazila: "Kishoreganj Sadar", upazila_bn: "কিশোরগঞ্জ সদর", postCode: "2300" },
            { upazila: "Kuliarchar", upazila_bn: "কুলিয়ারচর", postCode: "2346" },
            { upazila: "Mithamain", upazila_bn: "মিঠামইন", postCode: "2360" },
            { upazila: "Nikli", upazila_bn: "নিকলী", postCode: "2347" },
            { upazila: "Pakundia", upazila_bn: "পাকুন্দিয়া", postCode: "2326" },
            { upazila: "Tarail", upazila_bn: "তাড়াইল", postCode: "2316" },
          ],
        },
        {
          district: "Madaripur",
          district_bn: "মাদারীপুর",
          upazilas: [
            { upazila: "Madaripur Sadar", upazila_bn: "মাদারীপুর সদর", postCode: "7900" },
            { upazila: "Kalkini", upazila_bn: "কালকিনি", postCode: "7920" },
            { upazila: "Rajoir", upazila_bn: "রাজৈর", postCode: "7910" },
            { upazila: "Shibchar", upazila_bn: "শিবচর", postCode: "7930" },
          ],
        },
        {
          district: "Manikganj",
          district_bn: "মানিকগঞ্জ",
          upazilas: [
            { upazila: "Daulatpur", upazila_bn: "দৌলতপুর", postCode: "1860" },
            { upazila: "Ghior", upazila_bn: "ঘিওর", postCode: "1840" },
            { upazila: "Harirampur", upazila_bn: "হরিরামপুর", postCode: "1830" },
            { upazila: "Manikganj Sadar", upazila_bn: "মানিকগঞ্জ সদর", postCode: "1800" },
            { upazila: "Saturia", upazila_bn: "সাটুরিয়া", postCode: "1810" },
            { upazila: "Shivalaya", upazila_bn: "শিবালয়", postCode: "1850" },
            { upazila: "Singair", upazila_bn: "সিংগাইর", postCode: "1820" },
          ],
        },
        {
          district: "Munshiganj",
          district_bn: "মুন্সিগঞ্জ",
          upazilas: [
            { upazila: "Gazaria", upazila_bn: "গজারিয়া", postCode: "1510" },
            { upazila: "Lohajang", upazila_bn: "লৌহজং", postCode: "1530" },
            { upazila: "Munshiganj Sadar", upazila_bn: "মুন্সিগঞ্জ সদর", postCode: "1500" },
            { upazila: "Sirajdikhan", upazila_bn: "সিরাজদিখান", postCode: "1540" },
            { upazila: "Sreenagar", upazila_bn: "শ্রীনগর", postCode: "1550" },
            { upazila: "Tongibari", upazila_bn: "টঙ্গিবাড়ী", postCode: "1520" },
          ],
        },
        {
          district: "Narayanganj",
          district_bn: "নারায়ণগঞ্জ",
          city_corporations: [
              { name: "Narayanganj City Corporation", name_bn: "নারায়ণগঞ্জ সিটি কর্পোরেশন" }
          ],
          upazilas: [
            { upazila: "Araihazar", upazila_bn: "আড়াইহাজার", postCode: "1450" },
            { upazila: "Bandar", upazila_bn: "বন্দর", postCode: "1410" },
            { upazila: "Narayanganj Sadar", upazila_bn: "নারায়ণগঞ্জ সদর", postCode: "1400" },
            { upazila: "Rupganj", upazila_bn: "রূপগঞ্জ", postCode: "1460" },
            { upazila: "Sonargaon", upazila_bn: "সোনারগাঁও", postCode: "1440" },
          ],
        },
        {
          district: "Narsingdi",
          district_bn: "নরসিংদী",
          upazilas: [
            { upazila: "Belabo", upazila_bn: "বেলাবো", postCode: "1640" },
            { upazila: "Monohardi", upazila_bn: "মনোহরদী", postCode: "1650" },
            { upazila: "Narsingdi Sadar", upazila_bn: "নরসিংদী সদর", postCode: "1600" },
            { upazila: "Palash", upazila_bn: "পলাশ", postCode: "1610" },
            { upazila: "Raipura", upazila_bn: "রায়পুরা", postCode: "1630" },
            { upazila: "Shibpur", upazila_bn: "শিবপুর", postCode: "1620" },
          ],
        },
        {
          district: "Rajbari",
          district_bn: "রাজবাড়ী",
          upazilas: [
            { upazila: "Baliakandi", upazila_bn: "বালিয়াকান্দি", postCode: "7730" },
            { upazila: "Goalandaghat", upazila_bn: "গোয়ালন্দঘাট", postCode: "7710" },
            { upazila: "Pangsha", upazila_bn: "পাংশা", postCode: "7720" },
            { upazila: "Rajbari Sadar", upazila_bn: "রাজবাড়ী সদর", postCode: "7700" },
            { upazila: "Kalukhali", upazila_bn: "কালুখালী", postCode: "7721" },
          ],
        },
        {
          district: "Shariatpur",
          district_bn: "শরীয়তপুর",
          upazilas: [
            { upazila: "Bhedarganj", upazila_bn: "ভেদরগঞ্জ", postCode: "8030" },
            { upazila: "Damudya", upazila_bn: "ডামুড্যা", postCode: "8040" },
            { upazila: "Gosairhat", upazila_bn: "গোসাইরহাট", postCode: "8050" },
            { upazila: "Naria", upazila_bn: "নড়িয়া", postCode: "8020" },
            { upazila: "Shariatpur Sadar", upazila_bn: "শরীয়তপুর সদর", postCode: "8000" },
            { upazila: "Zajira", upazila_bn: "জাজিরা", postCode: "8010" },
          ],
        },
        {
          district: "Tangail",
          district_bn: "টাঙ্গাইল",
          upazilas: [
            { upazila: "Basail", upazila_bn: "বাসাইল", postCode: "1920" },
            { upazila: "Bhuapur", upazila_bn: "ভুয়াপুর", postCode: "1960" },
            { upazila: "Delduar", upazila_bn: "দেলদুয়ার", postCode: "1910" },
            { upazila: "Ghatail", upazila_bn: "ঘাটাইল", postCode: "1980" },
            { upazila: "Gopalpur", upazila_bn: "গোপালপুর", postCode: "1990" },
            { upazila: "Kalihati", upazila_bn: "কালিহাতী", postCode: "1970" },
            { upazila: "Madhupur", upazila_bn: "মধুপুর", postCode: "1996" },
            { upazila: "Mirzapur", upazila_bn: "মির্জাপুর", postCode: "1940" },
            { upazila: "Nagarpur", upazila_bn: "নাগরপুর", postCode: "1930" },
            { upazila: "Sakhipur", upazila_bn: "সখিপুর", postCode: "1950" },
            { upazila: "Tangail Sadar", upazila_bn: "টাঙ্গাইল সদর", postCode: "1900" },
            { upazila: "Dhanbari", upazila_bn: "ধনবাড়ী", postCode: "1997" },
          ],
        },
      ],
    },
    {
      division: "Khulna",
      division_bn: "খুলনা",
      districts: [
        {
          district: "Bagerhat",
          district_bn: "বাগেরহাট",
          upazilas: [
            { upazila: "Bagerhat Sadar", upazila_bn: "বাগেরহাট সদর", postCode: "9300" },
            { upazila: "Chitalmari", upazila_bn: "চিতলমারী", postCode: "9340" },
            { upazila: "Fakirhat", upazila_bn: "ফকিরহাট", postCode: "9330" },
            { upazila: "Kachua", upazila_bn: "কচুয়া", postCode: "9310" },
            { upazila: "Mollahat", upazila_bn: "মোল্লাহাট", postCode: "9330" },
            { upazila: "Mongla", upazila_bn: "মোংলা", postCode: "9350" },
            { upazila: "Morrelganj", upazila_bn: "মোড়েলগঞ্জ", postCode: "9320" },
            { upazila: "Rampal", upazila_bn: "রামপাল", postCode: "9340" },
            { upazila: "Sarankhola", upazila_bn: "শরণখোলা", postCode: "9321" },
          ],
        },
        {
          district: "Chuadanga",
          district_bn: "চুয়াডাঙ্গা",
          upazilas: [
            { upazila: "Alamdanga", upazila_bn: "আলমডাঙ্গা", postCode: "7210" },
            { upazila: "Chuadanga Sadar", upazila_bn: "চুয়াডাঙ্গা সদর", postCode: "7200" },
            { upazila: "Damurhuda", upazila_bn: "দামুড়হুদা", postCode: "7220" },
            { upazila: "Jibannagar", upazila_bn: "জীবননগর", postCode: "7230" },
          ],
        },
        {
          district: "Jessore",
          district_bn: "যশোর",
          upazilas: [
            { upazila: "Abhaynagar", upazila_bn: "অভয়নগর", postCode: "7460" },
            { upazila: "Bagherpara", upazila_bn: "বাঘারপাড়া", postCode: "7470" },
            { upazila: "Chaugachha", upazila_bn: "চৌগাছা", postCode: "7410" },
            { upazila: "Jhikargachha", upazila_bn: "ঝিকরগাছা", postCode: "7420" },
            { upazila: "Keshabpur", upazila_bn: "কেশবপুর", postCode: "7450" },
            { upazila: "Jessore Sadar", upazila_bn: "যশোর সদর", postCode: "7400" },
            { upazila: "Manirampur", upazila_bn: "মণিরামপুর", postCode: "7440" },
            { upazila: "Sharsha", upazila_bn: "শার্শা", postCode: "7430" },
          ],
        },
        {
          district: "Jhenaidah",
          district_bn: "ঝিনাইদহ",
          upazilas: [
            { upazila: "Harinakunda", upazila_bn: "হরিণাকুণ্ডু", postCode: "7310" },
            { upazila: "Jhenaidah Sadar", upazila_bn: "ঝিনাইদহ সদর", postCode: "7300" },
            { upazila: "Kaliganj", upazila_bn: "কালীগঞ্জ", postCode: "7350" },
            { upazila: "Kotchandpur", upazila_bn: "কোটচাঁদপুর", postCode: "7330" },
            { upazila: "Maheshpur", upazila_bn: "মহেশপুর", postCode: "7340" },
            { upazila: "Shailkupa", upazila_bn: "শৈলকুপা", postCode: "7320" },
          ],
        },
        {
          district: "Khulna",
          district_bn: "খুলনা",
          city_corporations: [
              { name: "Khulna City Corporation", name_bn: "খুলনা সিটি কর্পোরেশন" }
          ],
          upazilas: [
            { upazila: "Batiaghata", upazila_bn: "বটিয়াঘাটা", postCode: "9260" },
            { upazila: "Dacope", upazila_bn: "দাকোপ", postCode: "9270" },
            { upazila: "Dumuria", upazila_bn: "ডুমুরিয়া", postCode: "9250" },
            { upazila: "Dighalia", upazila_bn: "দিঘলিয়া", postCode: "9220" },
            { upazila: "Koyra", upazila_bn: "কয়রা", postCode: "9280" },
            { upazila: "Paikgachha", upazila_bn: "পাইকগাছা", postCode: "9280" },
            { upazila: "Phultala", upazila_bn: "ফুলতলা", postCode: "9210" },
            { upazila: "Rupsha", upazila_bn: "রূপসা", postCode: "9240" },
            { upazila: "Terokhada", upazila_bn: "তেরখাদা", postCode: "9230" },
            // Khulna City Corporation Thanas
            { upazila: "Daulatpur", upazila_bn: "দৌলতপুর", postCode: "9202" },
            { upazila: "Khalishpur", upazila_bn: "খালিশপুর", postCode: "9203" },
            { upazila: "Khan Jahan Ali", upazila_bn: "খান জাহান আলী", postCode: "9204" },
            { upazila: "Kotwali", upazila_bn: "কোতোয়ালী", postCode: "9100" },
            { upazila: "Sonadanga", upazila_bn: "সোনাডাঙ্গা", postCode: "9100" },
          ],
        },
        {
          district: "Kushtia",
          district_bn: "কুষ্টিয়া",
          upazilas: [
            { upazila: "Bheramara", upazila_bn: "ভেড়ামারা", postCode: "7040" },
            { upazila: "Daulatpur", upazila_bn: "দৌলতপুর", postCode: "7050" },
            { upazila: "Khoksa", upazila_bn: "খোকসা", postCode: "7030" },
            { upazila: "Kumarkhali", upazila_bn: "কুমারখালী", postCode: "7010" },
            { upazila: "Kushtia Sadar", upazila_bn: "কুষ্টিয়া সদর", postCode: "7000" },
            { upazila: "Mirpur", upazila_bn: "মিরপুর", postCode: "7020" },
          ],
        },
        {
          district: "Magura",
          district_bn: "মাগুরা",
          upazilas: [
            { upazila: "Magura Sadar", upazila_bn: "মাগুরা সদর", postCode: "7600" },
            { upazila: "Mohammadpur", upazila_bn: "محمدপুর", postCode: "7630" },
            { upazila: "Shalikha", upazila_bn: "শালিখা", postCode: "7620" },
            { upazila: "Sreepur", upazila_bn: "শ্রীপুর", postCode: "7610" },
          ],
        },
        {
          district: "Meherpur",
          district_bn: "মেহেরপুর",
          upazilas: [
            { upazila: "Gangni", upazila_bn: "গাংনী", postCode: "7110" },
            { upazila: "Meherpur Sadar", upazila_bn: "মেহেরপুর সদর", postCode: "7100" },
            { upazila: "Mujibnagar", upazila_bn: "মুজিবনগর", postCode: "7101" },
          ],
        },
        {
          district: "Narail",
          district_bn: "নড়াইল",
          upazilas: [
            { upazila: "Kalia", upazila_bn: "কালিয়া", postCode: "8030" },
            { upazila: "Lohagara", upazila_bn: "লোহাগড়া", postCode: "8020" },
            { upazila: "Narail Sadar", upazila_bn: "নড়াইল সদর", postCode: "8000" },
          ],
        },
        {
          district: "Satkhira",
          district_bn: "সাতক্ষীরা",
          upazilas: [
            { upazila: "Assasuni", upazila_bn: "আশাশুনি", postCode: "9440" },
            { upazila: "Debhata", upazila_bn: "দেবহাটা", postCode: "9430" },
            { upazila: "Kalaroa", upazila_bn: "কলারোয়া", postCode: "9410" },
            { upazila: "Kaliganj", upazila_bn: "কালীগঞ্জ", postCode: "9420" },
            { upazila: "Satkhira Sadar", upazila_bn: "সাতক্ষীরা সদর", postCode: "9400" },
            { upazila: "Shyamnagar", upazila_bn: "শ্যামনগর", postCode: "9450" },
            { upazila: "Tala", upazila_bn: "তালা", postCode: "9410" },
          ],
        },
      ],
    },
    {
      division: "Mymensingh",
      division_bn: "ময়মনসিংহ",
      districts: [
        {
          district: "Jamalpur",
          district_bn: "জামালপুর",
          upazilas: [
            { upazila: "Baksiganj", upazila_bn: "বকশীগঞ্জ", postCode: "2140" },
            { upazila: "Dewanganj", upazila_bn: "দেওয়ানগঞ্জ", postCode: "2130" },
            { upazila: "Islampur", upazila_bn: "ইসলামপুর", postCode: "2120" },
            { upazila: "Jamalpur Sadar", upazila_bn: "জামালপুর সদর", postCode: "2000" },
            { upazila: "Madarganj", upazila_bn: "মাদারগঞ্জ", postCode: "2010" },
            { upazila: "Melandaha", upazila_bn: "মেলান্দহ", postCode: "2010" },
            { upazila: "Sarishabari", upazila_bn: "সরিষাবাড়ী", postCode: "2050" },
          ],
        },
        {
          district: "Mymensingh",
          district_bn: "ময়মনসিংহ",
          city_corporations: [
              { name: "Mymensingh City Corporation", name_bn: "ময়মনসিংহ সিটি কর্পোরেশন" }
          ],
          upazilas: [
            { upazila: "Bhaluka", upazila_bn: "ভালুকা", postCode: "2240" },
            { upazila: "Dhobaura", upazila_bn: "ধোবাউড়া", postCode: "2260" },
            { upazila: "Fulbaria", upazila_bn: "ফুলবাড়ীয়া", postCode: "2250" },
            { upazila: "Gaffargaon", upazila_bn: "গফরগাঁও", postCode: "2230" },
            { upazila: "Gauripur", upazila_bn: "গৌরীপুর", postCode: "2270" },
            { upazila: "Haluaghat", upazila_bn: "হালুয়াঘাট", postCode: "2260" },
            { upazila: "Ishwarganj", upazila_bn: "ঈশ্বরগঞ্জ", postCode: "2280" },
            { upazila: "Mymensingh Sadar", upazila_bn: "ময়মনসিংহ সদর", postCode: "2200" },
            { upazila: "Muktagachha", upazila_bn: "মুক্তাগাছা", postCode: "2210" },
            { upazila: "Nandail", upazila_bn: "নান্দাইল", postCode: "2290" },
            { upazila: "Phulpur", upazila_bn: "ফুলপুর", postCode: "2250" },
            { upazila: "Trishal", upazila_bn: "ত্রিশাল", postCode: "2220" },
            { upazila: "Tara Khanda", upazila_bn: "তারাকান্দা", postCode: "2251" },
          ],
        },
        {
          district: "Netrokona",
          district_bn: "নেত্রকোণা",
          upazilas: [
            { upazila: "Atpara", upazila_bn: "আটপাড়া", postCode: "2470" },
            { upazila: "Barhatta", upazila_bn: "বারহাট্টা", postCode: "2440" },
            { upazila: "Durgapur", upazila_bn: "দুর্গাপুর", postCode: "2430" },
            { upazila: "Khaliajuri", upazila_bn: "খালিয়াজুড়ি", postCode: "2460" },
            { upazila: "Kalmakanda", upazila_bn: "কলমাকান্দা", postCode: "2430" },
            { upazila: "Kendua", upazila_bn: "কেন্দুয়া", postCode: "2480" },
            { upazila: "Madan", upazila_bn: "মদন", postCode: "2450" },
            { upazila: "Mohanganj", upazila_bn: "মোহনগঞ্জ", postCode: "2440" },
            { upazila: "Netrokona Sadar", upazila_bn: "নেত্রকোণা সদর", postCode: "2400" },
            { upazila: "Purbadhala", upazila_bn: "পূর্বধলা", postCode: "2410" },
          ],
        },
        {
          district: "Sherpur",
          district_bn: "শেরপুর",
          upazilas: [
            { upazila: "Jhenaigati", upazila_bn: "ঝিনাইগাতী", postCode: "2120" },
            { upazila: "Nakla", upazila_bn: "নকলা", postCode: "2150" },
            { upazila: "Nalitabari", upazila_bn: "নালিতাবাড়ী", postCode: "2110" },
            { upazila: "Sherpur Sadar", upazila_bn: "শেরপুর সদর", postCode: "2100" },
            { upazila: "Sreebardi", upazila_bn: "শ্রীবরদী", postCode: "2110" },
          ],
        },
      ],
    },
    {
      division: "Rajshahi",
      division_bn: "রাজশাহী",
      districts: [
        {
          district: "Bogra",
          district_bn: "বগুড়া",
          upazilas: [
            { upazila: "Adamdighi", upazila_bn: "আদমদীঘি", postCode: "5890" },
            { upazila: "Bogra Sadar", upazila_bn: "বগুড়া সদর", postCode: "5800" },
            { upazila: "Dhunat", upazila_bn: "ধুনট", postCode: "5850" },
            { upazila: "Dhupchanchia", upazila_bn: "দুপচাঁচিয়া", postCode: "5880" },
            { upazila: "Gabtali", upazila_bn: "গাবতলী", postCode: "5820" },
            { upazila: "Kahaloo", upazila_bn: "কাহালু", postCode: "5870" },
            { upazila: "Nandigram", upazila_bn: "নন্দীগ্রাম", postCode: "5860" },
            { upazila: "Sariakandi", upazila_bn: "সারিয়াকান্দি", postCode: "5830" },
            { upazila: "Shajahanpur", upazila_bn: "শাজাহানপুর", postCode: "5801" },
            { upazila: "Sherpur", upazila_bn: "শেরপুর", postCode: "5840" },
            { upazila: "Shibganj", upazila_bn: "শিবগঞ্জ", postCode: "5810" },
            { upazila: "Sonatola", upazila_bn: "সোনাতলা", postCode: "5826" },
          ],
        },
        {
          district: "Joypurhat",
          district_bn: "জয়পুরহাট",
          upazilas: [
            { upazila: "Akkelpur", upazila_bn: "আক্কেলপুর", postCode: "5940" },
            { upazila: "Joypurhat Sadar", upazila_bn: "জয়পুরহাট সদর", postCode: "5900" },
            { upazila: "Kalai", upazila_bn: "কালাই", postCode: "5930" },
            { upazila: "Khetlal", upazila_bn: "ক্ষেতলাল", postCode: "5920" },
            { upazila: "Panchbibi", upazila_bn: "পাঁচবিবি", postCode: "5910" },
          ],
        },
        {
          district: "Naogaon",
          district_bn: "নওগাঁ",
          upazilas: [
            { upazila: "Atrai", upazila_bn: "আত্রাই", postCode: "6580" },
            { upazila: "Badalgachhi", upazila_bn: "বদলগাছী", postCode: "6570" },
            { upazila: "Dhamoirhat", upazila_bn: "ধামইরহাট", postCode: "6550" },
            { upazila: "Manda", upazila_bn: "মান্দা", postCode: "6510" },
            { upazila: "Mohadevpur", upazila_bn: "মহাদেবপুর", postCode: "6530" },
            { upazila: "Naogaon Sadar", upazila_bn: "নওগাঁ সদর", postCode: "6500" },
            { upazila: "Niamatpur", upazila_bn: "নিয়ামতপুর", postCode: "6520" },
            { upazila: "Patnitala", upazila_bn: "পত্নীতলা", postCode: "6540" },
            { upazila: "Porsha", upazila_bn: "পোরশা", postCode: "6540" },
            { upazila: "Raninagar", upazila_bn: "রাণীনগর", postCode: "6590" },
            { upazila: "Sapahar", upazila_bn: "সাপাহার", postCode: "6560" },
          ],
        },
        {
          district: "Natore",
          district_bn: "নাটোর",
          upazilas: [
            { upazila: "Bagatipara", upazila_bn: "বাগাতিপাড়া", postCode: "6420" },
            { upazila: "Baraigram", upazila_bn: "বড়াইগ্রাম", postCode: "6430" },
            { upazila: "Gurudaspur", upazila_bn: "গুরুদাসপুর", postCode: "6440" },
            { upazila: "Lalpur", upazila_bn: "লালপুর", postCode: "6420" },
            { upazila: "Natore Sadar", upazila_bn: "নাটোর সদর", postCode: "6400" },
            { upazila: "Singra", upazila_bn: "সিংড়া", postCode: "6450" },
            { upazila: "Naldanga", upazila_bn: "নলডাঙ্গা", postCode: "6401" },
          ],
        },
        {
          district: "Chapainawabganj",
          district_bn: "চাঁপাইনবাবগঞ্জ",
          upazilas: [
            { upazila: "Bholahat", upazila_bn: "ভোলাহাট", postCode: "6330" },
            { upazila: "Gomastapur", upazila_bn: "গোমস্তাপুর", postCode: "6320" },
            { upazila: "Nachole", upazila_bn: "নাচোল", postCode: "6310" },
            { upazila: "Nawabganj Sadar", upazila_bn: "নবাবগঞ্জ সদর", postCode: "6300" },
            { upazila: "Shibganj", upazila_bn: "শিবগঞ্জ", postCode: "6340" },
          ],
        },
        {
          district: "Pabna",
          district_bn: "পাবনা",
          upazilas: [
            { upazila: "Atgharia", upazila_bn: "আটঘরিয়া", postCode: "6610" },
            { upazila: "Bera", upazila_bn: "বেড়া", postCode: "6680" },
            { upazila: "Bhangura", upazila_bn: "ভাঙ্গুড়া", postCode: "6640" },
            { upazila: "Chatmohar", upazila_bn: "চাটমোহর", postCode: "6630" },
            { upazila: "Faridpur", upazila_bn: "ফরিদপুর", postCode: "6650" },
            { upazila: "Ishwardi", upazila_bn: "ঈশ্বরদী", postCode: "6620" },
            { upazila: "Pabna Sadar", upazila_bn: "পাবনা সদর", postCode: "6600" },
            { upazila: "Santhia", upazila_bn: "সাঁথিয়া", postCode: "6670" },
            { upazila: "Sujanagar", upazila_bn: "সুজানগর", postCode: "6660" },
          ],
        },
        {
          district: "Rajshahi",
          district_bn: "রাজশাহী",
          city_corporations: [
              { name: "Rajshahi City Corporation", name_bn: "রাজশাহী সিটি কর্পোরেশন" }
          ],
          upazilas: [
            { upazila: "Bagha", upazila_bn: "বাঘা", postCode: "6280" },
            { upazila: "Bagmara", upazila_bn: "বাগমারা", postCode: "6250" },
            { upazila: "Charghat", upazila_bn: "চারঘাট", postCode: "6270" },
            { upazila: "Durgapur", upazila_bn: "দুর্গাপুর", postCode: "6240" },
            { upazila: "Godagari", upazila_bn: "গোদাগাড়ী", postCode: "6220" },
            { upazila: "Mohanpur", upazila_bn: "মোহনপুর", postCode: "6220" },
            { upazila: "Paba", upazila_bn: "পবা", postCode: "6210" },
            { upazila: "Puthia", upazila_bn: "পুঠিয়া", postCode: "6230" },
            { upazila: "Tanore", upazila_bn: "তানোর", postCode: "6210" },
            // Rajshahi City Corporation Thanas
            { upazila: "Boalia", upazila_bn: "বোয়ালিয়া", postCode: "6100" },
            { upazila: "Matihar", upazila_bn: "মতিহার", postCode: "6204" },
            { upazila: "Rajpara", upazila_bn: "রাজপাড়া", postCode: "6000" },
            { upazila: "Shah Makhdum", upazila_bn: "শাহ মখদুম", postCode: "6201" },
          ],
        },
        {
          district: "Sirajganj",
          district_bn: "সিরাজগঞ্জ",
          upazilas: [
            { upazila: "Belkuchi", upazila_bn: "বেলকুচি", postCode: "6740" },
            { upazila: "Chauhali", upazila_bn: "চৌহালি", postCode: "6750" },
            { upazila: "Kamarkhanda", upazila_bn: "কামারখন্দ", postCode: "6730" },
            { upazila: "Kazipur", upazila_bn: "কাজীপুর", postCode: "6710" },
            { upazila: "Raiganj", upazila_bn: "রায়গঞ্জ", postCode: "6720" },
            { upazila: "Shahjadpur", upazila_bn: "শাহজাদপুর", postCode: "6770" },
            { upazila: "Sirajganj Sadar", upazila_bn: "সিরাজগঞ্জ সদর", postCode: "6700" },
            { upazila: "Tarash", upazila_bn: "তাড়াশ", postCode: "6780" },
            { upazila: "Ullahpara", upazila_bn: "উল্লাপাড়া", postCode: "6760" },
          ],
        },
      ],
    },
    {
      division: "Rangpur",
      division_bn: "রংপুর",
      districts: [
        {
          district: "Dinajpur",
          district_bn: "দিনাজপুর",
          upazilas: [
            { upazila: "Biral", upazila_bn: "বিড়াল", postCode: "5210" },
            { upazila: "Birampur", upazila_bn: "বিরামপুর", postCode: "5260" },
            { upazila: "Birganj", upazila_bn: "বীরগঞ্জ", postCode: "5220" },
            { upazila: "Bochaganj", upazila_bn: "বোচাগঞ্জ", postCode: "5210" },
            { upazila: "Chirirbandar", upazila_bn: "চিরিরবন্দর", postCode: "5240" },
            { upazila: "Phulbari", upazila_bn: "ফুলবাড়ী", postCode: "5250" },
            { upazila: "Ghoraghat", upazila_bn: "ঘোড়াঘাট", postCode: "5280" },
            { upazila: "Hakimpur", upazila_bn: "হাকিমপুর", postCode: "5270" },
            { upazila: "Kaharole", upazila_bn: "কাহারোল", postCode: "5221" },
            { upazila: "Khansama", upazila_bn: "খানসামা", postCode: "5230" },
            { upazila: "Dinajpur Sadar", upazila_bn: "দিনাজপুর সদর", postCode: "5200" },
            { upazila: "Nawabganj", upazila_bn: "নবাবগঞ্জ", postCode: "5290" },
            { upazila: "Parbatipur", upazila_bn: "পার্বতীপুর", postCode: "5250" },
          ],
        },
        {
          district: "Gaibandha",
          district_bn: "গাইবান্ধা",
          upazilas: [
            { upazila: "Phulchhari", upazila_bn: "ফুলছড়ি", postCode: "5720" },
            { upazila: "Gaibandha Sadar", upazila_bn: "গাইবান্ধা সদর", postCode: "5700" },
            { upazila: "Gobindaganj", upazila_bn: "গোবিন্দগঞ্জ", postCode: "5740" },
            { upazila: "Palashbari", upazila_bn: "পলাশবাড়ী", postCode: "5730" },
            { upazila: "Sadullapur", upazila_bn: "সাদুল্লাপুর", postCode: "5710" },
            { upazila: "Saghata", upazila_bn: "সাঘাটা", postCode: "5720" },
            { upazila: "Sundarganj", upazila_bn: "সুন্দরগঞ্জ", postCode: "5720" },
          ],
        },
        {
          district: "Kurigram",
          district_bn: "কুড়িগ্রাম",
          upazilas: [
            { upazila: "Bhurungamari", upazila_bn: "ভুরুঙ্গামারী", postCode: "5670" },
            { upazila: "Char Rajibpur", upazila_bn: "চর রাজিবপুর", postCode: "5650" },
            { upazila: "Chilmari", upazila_bn: "চিলমারী", postCode: "5640" },
            { upazila: "Phulbari", upazila_bn: "ফুলবাড়ী", postCode: "5680" },
            { upazila: "Kurigram Sadar", upazila_bn: "কুড়িগ্রাম সদর", postCode: "5600" },
            { upazila: "Nageshwari", upazila_bn: "নাগেশ্বরী", postCode: "5660" },
            { upazila: "Rajarhat", upazila_bn: "রাজারহাট", postCode: "5610" },
            { upazila: "Raomari", upazila_bn: "রৌমারী", postCode: "5650" },
            { upazila: "Ulipur", upazila_bn: "উলিপুর", postCode: "5620" },
          ],
        },
        {
          district: "Lalmonirhat",
          district_bn: "লালমনিরহাট",
          upazilas: [
            { upazila: "Aditmari", upazila_bn: "আদিতমারী", postCode: "5510" },
            { upazila: "Hatibandha", upazila_bn: "হাতীবান্ধা", postCode: "5530" },
            { upazila: "Kaliganj", upazila_bn: "কালীগঞ্জ", postCode: "5520" },
            { upazila: "Lalmonirhat Sadar", upazila_bn: "লালমনিরহাট সদর", postCode: "5500" },
            { upazila: "Patgram", upazila_bn: "পাটগ্রাম", postCode: "5540" },
          ],
        },
        {
          district: "Nilphamari",
          district_bn: "নীলফামারী",
          upazilas: [
            { upazila: "Dimla", upazila_bn: "ডিমলা", postCode: "5350" },
            { upazila: "Domar", upazila_bn: "ডোমার", postCode: "5340" },
            { upazila: "Jaldhaka", upazila_bn: "জলঢাকা", postCode: "5330" },
            { upazila: "Kishoreganj", upazila_bn: "কিশোরগঞ্জ", postCode: "5320" },
            { upazila: "Nilphamari Sadar", upazila_bn: "নীলফামারী সদর", postCode: "5300" },
            { upazila: "Saidpur", upazila_bn: "সৈয়দপুর", postCode: "5310" },
          ],
        },
        {
          district: "Panchagarh",
          district_bn: "পঞ্চগড়",
          upazilas: [
            { upazila: "Atwari", upazila_bn: "আটোয়ারী", postCode: "5040" },
            { upazila: "Boda", upazila_bn: "বোদা", postCode: "5010" },
            { upazila: "Debiganj", upazila_bn: "দেবীগঞ্জ", postCode: "5020" },
            { upazila: "Panchagarh Sadar", upazila_bn: "পঞ্চগড় সদর", postCode: "5000" },
            { upazila: "Tetulia", upazila_bn: "তেতুলিয়া", postCode: "5030" },
          ],
        },
        {
          district: "Rangpur",
          district_bn: "রংপুর",
          city_corporations: [
              { name: "Rangpur City Corporation", name_bn: "রংপুর সিটি কর্পোরেশন" }
          ],
          upazilas: [
            { upazila: "Badarganj", upazila_bn: "বদরগঞ্জ", postCode: "5430" },
            { upazila: "Gangachhara", upazila_bn: "গঙ্গাচড়া", postCode: "5410" },
            { upazila: "Kaunia", upazila_bn: "কাউনিয়া", postCode: "5440" },
            { upazila: "Rangpur Sadar", upazila_bn: "রংপুর সদর", postCode: "5400" },
            { upazila: "Mithapukur", upazila_bn: "মিঠাপুকুর", postCode: "5460" },
            { upazila: "Pirgachha", upazila_bn: "পীরগাছা", postCode: "5450" },
            { upazila: "Pirganj", upazila_bn: "পীরগঞ্জ", postCode: "5470" },
            { upazila: "Taraganj", upazila_bn: "তারাগঞ্জ", postCode: "5420" },
          ],
        },
        {
          district: "Thakurgaon",
          district_bn: "ঠাকুরগাঁও",
          upazilas: [
            { upazila: "Baliadangi", upazila_bn: "বালিয়াডাঙ্গী", postCode: "5110" },
            { upazila: "Haripur", upazila_bn: "হরিপুর", postCode: "5120" },
            { upazila: "Pirganj", upazila_bn: "পীরগঞ্জ", postCode: "5130" },
            { upazila: "Ranisankail", upazila_bn: "রাণীশংকৈল", postCode: "5120" },
            { upazila: "Thakurgaon Sadar", upazila_bn: "ঠাকুরগাঁও সদর", postCode: "5100" },
          ],
        },
      ],
    },
    {
      division: "Sylhet",
      division_bn: "সিলেট",
      districts: [
        {
          district: "Habiganj",
          district_bn: "হবিগঞ্জ",
          upazilas: [
            { upazila: "Ajmiriganj", upazila_bn: "আজমিরীগঞ্জ", postCode: "3360" },
            { upazila: "Bahubal", upazila_bn: "বাহুবল", postCode: "3310" },
            { upazila: "Baniachang", upazila_bn: "বানিয়াচং", postCode: "3350" },
            { upazila: "Chunarughat", upazila_bn: "চুনারুঘাট", postCode: "3320" },
            { upazila: "Habiganj Sadar", upazila_bn: "হবিগঞ্জ সদর", postCode: "3300" },
            { upazila: "Lakhai", upazila_bn: "লাখাই", postCode: "3340" },
            { upazila: "Madhabpur", upazila_bn: "মাধবপুর", postCode: "3330" },
            { upazila: "Nabiganj", upazila_bn: "নবীগঞ্জ", postCode: "3370" },
          ],
        },
        {
          district: "Moulvibazar",
          district_bn: "মৌলভীবাজার",
          upazilas: [
            { upazila: "Barlekha", upazila_bn: "বড়লেখা", postCode: "3250" },
            { upazila: "Juri", upazila_bn: "জুড়ী", postCode: "3251" },
            { upazila: "Kamalganj", upazila_bn: "কমলগঞ্জ", postCode: "3220" },
            { upazila: "Kulaura", upazila_bn: "কুলাউড়া", postCode: "3230" },
            { upazila: "Moulvibazar Sadar", upazila_bn: "মৌলভীবাজার সদর", postCode: "3200" },
            { upazila: "Rajnagar", upazila_bn: "রাজনগর", postCode: "3240" },
            { upazila: "Sreemangal", upazila_bn: "শ্রীমঙ্গল", postCode: "3210" },
          ],
        },
        {
          district: "Sunamganj",
          district_bn: "সুনামগঞ্জ",
          upazilas: [
            { upazila: "Bishwambarpur", upazila_bn: "বিশ্বম্ভরপুর", postCode: "3010" },
            { upazila: "Chhatak", upazila_bn: "ছাতক", postCode: "3080" },
            { upazila: "Derai", upazila_bn: "দিরাই", postCode: "3040" },
            { upazila: "Dharampara", upazila_bn: "ধর্মপাশা", postCode: "3050" },
            { upazila: "Dowarabazar", upazila_bn: "দোয়ারাবাজার", postCode: "3070" },
            { upazila: "Jagannathpur", upazila_bn: "জগন্নাথপুর", postCode: "3060" },
            { upazila: "Jamalganj", upazila_bn: "জামালগঞ্জ", postCode: "3020" },
            { upazila: "Sullah", upazila_bn: "শাল্লা", postCode: "3030" },
            { upazila: "Sunamganj Sadar", upazila_bn: "সুনামগঞ্জ সদর", postCode: "3000" },
            { upazila: "Tahirpur", upazila_bn: "তাহিরপুর", postCode: "3010" },
            { upazila: "South Sunamganj", upazila_bn: "দক্ষিণ সুনামগঞ্জ", postCode: "3061" },
          ],
        },
        {
          district: "Sylhet",
          district_bn: "সিলেট",
          city_corporations: [
              { name: "Sylhet City Corporation", name_bn: "সিলেট সিটি কর্পোরেশন" }
          ],
          upazilas: [
            { upazila: "Balaganj", upazila_bn: "বালাগঞ্জ", postCode: "3120" },
            { upazila: "Beanibazar", upazila_bn: "বিয়ানীবাজার", postCode: "3170" },
            { upazila: "Bishwanath", upazila_bn: "বিশ্বনাথ", postCode: "3130" },
            { upazila: "Companiganj", upazila_bn: "কোম্পানীগঞ্জ", postCode: "3140" },
            { upazila: "Fenchuganj", upazila_bn: "ফেঞ্চুগঞ্জ", postCode: "3110" },
            { upazila: "Golapganj", upazila_bn: "গোলাপগঞ্জ", postCode: "3160" },
            { upazila: "Gowainghat", upazila_bn: "গোয়াইনঘাট", postCode: "3150" },
            { upazila: "Jaintiapur", upazila_bn: "জৈন্তাপুর", postCode: "3156" },
            { upazila: "Kanaighat", upazila_bn: "কানাইঘাট", postCode: "3180" },
            { upazila: "Sylhet Sadar", upazila_bn: "সিলেট সদর", postCode: "3100" },
            { upazila: "Zakiganj", upazila_bn: "জকিগঞ্জ", postCode: "3190" },
            { upazila: "South Surma", upazila_bn: "দক্ষিণ সুরমা", postCode: "3100" },
          ],
        },
      ],
    },
  ];